# Generated by Django 2.2 on 2022-07-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantree_app', '0002_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
